[package]
name = "nacl"
version = "0.4.0"
edition = "2021"
description = "Rust version of NaCl Cryptographic library with Scrypt added"
authors = ["3NSoft Inc. <hq@3nsoft.com>"]
license = "LGPL-3.0+"
repository = "https://github.com/3nsoft/rust-nacl"

[dependencies]
